---
# Main orchestration playbook for Kubernetes cluster deployment
- import_playbook: playbooks/01-system-setup.yml
- import_playbook: playbooks/02-container-runtime.yml
- import_playbook: playbooks/03-kubernetes-install.yml
- import_playbook: playbooks/04-kube-vip-setup.yml
- import_playbook: playbooks/05-cluster-init.yml
- import_playbook: playbooks/06-network-setup.yml
- import_playbook: playbooks/07-join-masters.yml
- import_playbook: playbooks/08-join-workers.yml
- import_playbook: playbooks/09-finalize-cluster.yml