apiVersion: v1
kind: Pod
metadata:
  name: gitea
  namespace: gitea
  labels:
    app: gitea
spec:
  containers:
  - name: gitea
    image: gitea/gitea:latest
    ports:
    - containerPort: 3000
    env:
    - name: GITEA__database__DB_TYPE
      value: "sqlite3"
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: gitea
spec:
  selector:
    app: gitea
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
  type: NodePort